import Foundation

#if os(macOS)
    import AppKit
#elseif canImport(UIKit)
    import UIKit
#endif

@MainActor
protocol ClipboardService {
    @discardableResult
    func copy(_ text: String, transient: Bool) -> Bool
}

extension ClipboardService {
    @discardableResult
    func copy(_ text: String) -> Bool {
        copy(text, transient: false)
    }
}

@MainActor
final class SystemClipboardService: ClipboardService {
    #if os(macOS)
        private let pasteboard: NSPasteboard
        private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
        private static let transientType = NSPasteboard.PasteboardType(
            "org.nspasteboard.TransientType")
        private static let autoGeneratedType = NSPasteboard.PasteboardType(
            "org.nspasteboard.AutoGeneratedType")
        private static let concealedType = NSPasteboard.PasteboardType(
            "org.nspasteboard.ConcealedType")

        init(pasteboard: NSPasteboard = .general) {
            self.pasteboard = pasteboard
        }
    #endif

    @discardableResult
    func copy(_ text: String, transient: Bool) -> Bool {
        #if os(macOS)
            let changeCountBefore = pasteboard.changeCount
            emitClipboardTrace(
                stage: "copy_begin",
                details:
                    "transient=\(transient) textLength=\(text.count) changeCountBefore=\(changeCountBefore)"
            )

            pasteboard.clearContents()

            guard pasteboard.setString(text, forType: .string) else {
                AppLogger.error(
                    "Failed to write text to clipboard (setString returned false)",
                    category: .general
                )
                emitClipboardTrace(
                    stage: "copy_end",
                    details:
                        "success=false transient=\(transient) textLength=\(text.count) changeCountBefore=\(changeCountBefore) changeCountAfter=\(pasteboard.changeCount)"
                )
                return false
            }

            if let bundleIdentifier = Bundle.main.bundleIdentifier {
                _ = pasteboard.setString(bundleIdentifier, forType: Self.sourceType)
            }
            if transient {
                _ = pasteboard.setData(Data(), forType: Self.transientType)
                _ = pasteboard.setData(Data(), forType: Self.autoGeneratedType)
                _ = pasteboard.setData(Data(), forType: Self.concealedType)
            }

            emitClipboardTrace(
                stage: "copy_end",
                details:
                    "success=true transient=\(transient) textLength=\(text.count) changeCountBefore=\(changeCountBefore) changeCountAfter=\(pasteboard.changeCount)"
            )
            return true
        #elseif canImport(UIKit)
            UIPasteboard.general.string = text
            return true
        #endif
    }

    #if os(macOS)
        private func emitClipboardTrace(stage: String, details: String) {
            AppLogger.info(
                "ClipboardTrace stage=\(stage) \(details)",
                category: .perfTrace
            )
        }
    #endif
}
