included:
  - Public/Stet/StetMac
  - Public/Stet/StetMacTests
  - Public/Stet/StetMacUITests
  - Public/Stet/StetVisuals
  - Private/StetMobile/StetKeyboard
  - Private/StetMobile/StetLiveActivity
  - Private/StetMobile/StetMobile
  - Private/StetMobile/StetMobileTests
  - Private/StetMobile/StetMobileUITests

excluded:
  - Public/Stet/build
  - Public/Stet/.derivedData
  - Private/StetMobile/build
  - Private/StetMobile/.build
  - Private/StetMobile/.runtime
  - StetMobile

only_rules:
  - empty_count
  - force_cast
  - force_try

reporter: github-actions-logging
