included:
  - apps/mac/Stet
  - apps/mac/StetTests
  - apps/mac/StetUITests
  - apps/mac/StetVisuals

excluded:
  - apps/mac/build
  - apps/mac/.derivedData

only_rules:
  - empty_count
  - force_cast
  - force_try

reporter: github-actions-logging
