included:
  - StetMac
  - StetMacTests
  - StetMacUITests
  - StetVisuals
  - StetMobile/StetKeyboard
  - StetMobile/StetLiveActivity
  - StetMobile/StetMobile
  - StetMobile/StetMobileTests
  - StetMobile/StetMobileUITests

excluded:
  - build
  - .derivedData
  - StetMobile/build
  - StetMobile/.build
  - StetMobile/.runtime

only_rules:
  - empty_count
  - force_cast
  - force_try

reporter: github-actions-logging
