import { SupabaseClient } from "@supabase/supabase-js";
import { ApiError } from "../error.ts";
import { log } from "../log.ts";
import { GroqModels, OpenAIModels } from "../providers/models.ts";
import type { AIProvider } from "../providers/provider.ts";
import type { RelayBillingBackend } from "../billing_backend.ts";

const DEFAULT_REWRITE_PROMPT = `
You are a conservative transcript editor.

Your job is to lightly clean raw speech transcripts while strictly preserving the speaker's exact meaning, sentence structure, emphasis, and tone.

Follow these rules strictly:
1. Punctuation & Capitalization: You MUST add appropriate punctuation (commas, periods, question marks, etc.) and capitalization to make the transcript readable. This does not violate the minimal edits rule.
2. Minimal Edits: Make the smallest possible changes. Do not rewrite for elegance, professionalism, or concision. Do not translate.
3. Fix Errors: Since the input is generated by a speech-to-text system, it inevitably contains phonetic typos, homophones, or misheard words. You must reasonably infer the correct words based on context and fix these transcription errors. Additionally, remove non-lexical filler words (e.g., "um", "uh") and obvious transcription noise.
4. Keep Meaningful Repetitions: Do not remove repeated words or phrases if they plausibly reflect hesitation, emphasis, self-correction, or intentional restatement. Only remove clearly accidental disfluencies (e.g., "the the", "we should should").
5. Preserve Corrections: Keep verbal self-corrections intact (e.g., "not Beijing, Shanghai" or "Tuesday-sorry, Wednesday").
6. No Structural Changes: Do not combine, summarize, reorganize sentences, or add unsaid information.
7. Output Format: Keep the output as plain text only. You may use simple numbering when the spoken content is clearly a sequence of steps. Do not use bullets, headings, code fences, backticks, or any other special formatting.
8. Default to Original: If uncertain about an edit, keep the original wording. If the transcript is already acceptable, return it with minimal or no changes.

Output only the cleaned transcript, making sure to add appropriate punctuation in all the right places.
`.trim();

export function buildRewritePrompt(options?: {
  customPrompt?: string;
  preferredSpellings?: string[];
}): string {
  let prompt = options?.customPrompt || DEFAULT_REWRITE_PROMPT;

  if (options?.preferredSpellings && options.preferredSpellings.length > 0) {
    prompt +=
      ` Preserve the exact spelling of these names, brands, jargon, and technical terms when they appear or are clearly intended: ${
        options.preferredSpellings.join(", ")
      }.`;
  }

  return prompt;
}

export async function performRewrite(args: {
  requestId: string;
  admin: SupabaseClient;
  userId: string;
  rawText: string;
  provider: AIProvider;
  providerName: "openai" | "groq";
  customPrompt?: string;
  preferredSpellings?: string[];
  billingBackend: RelayBillingBackend;
}) {
  const input = args.rawText?.trim();
  if (!input) {
    log("info", "rewrite_skipped_empty", args.requestId, {
      userId: args.userId,
    });
    return { text: "", billedCredits: 0 };
  }

  const systemPrompt = buildRewritePrompt({
    customPrompt: args.customPrompt,
    preferredSpellings: args.preferredSpellings,
  });
  const usage = await args.billingBackend.beginRewriteUsage({
    admin: args.admin,
    userId: args.userId,
    requestId: args.requestId,
    provider: args.providerName,
    modelId: args.providerName === "groq"
      ? GroqModels.REWRITE
      : OpenAIModels.REWRITE,
    inputText: input,
  });
  const rewriteModelId = args.providerName === "groq"
    ? GroqModels.REWRITE
    : OpenAIModels.REWRITE;

  log("info", "rewrite_started", args.requestId, {
    userId: args.userId,
    inputLength: input.length,
    rewriteModel: rewriteModelId,
    hasPreferredSpellings: Boolean(args.preferredSpellings?.length),
    reservedCredits: usage.reserved_credits,
  });

  try {
    const result = await args.provider.rewrite(input, systemPrompt);
    const settlement = await args.billingBackend.finalizeRewriteUsage({
      admin: args.admin,
      usageEventId: usage.usage_event_id,
      provider: args.providerName,
      inputText: input,
      outputText: result.text,
      usage: result.usage,
      upstreamStatus: 200,
    });

    log("info", "rewrite_completed", args.requestId, {
      userId: args.userId,
      rewriteModel: rewriteModelId,
      outputLength: result.text.length,
      billedCredits: settlement.billedCredits,
    });

    return {
      text: result.text,
      billedCredits: settlement.billedCredits,
    };
  } catch (error) {
    await args.billingBackend.refundUsage({
      admin: args.admin,
      usageEventId: usage.usage_event_id,
      upstreamStatus: 502,
    }).catch(() => {});

    log("error", "rewrite_failed", args.requestId, {
      userId: args.userId,
      error: error instanceof Error ? error.message : "unknown_ai_error",
    });

    throw new ApiError(
      502,
      "ai_rewrite_error",
      "The AI failed to polish your transcript.",
    );
  }
}
