import Foundation

enum MacPreferences {
    nonisolated static let onboardingCompleted = "mac.onboardingCompleted"
    nonisolated static let pauseMediaDuringDictation = "mac.pauseMediaDuringDictation"
    nonisolated static let transcriptionProvider = "mac.transcriptionProvider"
    nonisolated static let aiExecutionMode = "mac.aiExecutionMode"
    nonisolated static let rewriteEnabled = "mac.rewriteEnabled"
    nonisolated static let dictationLanguageMode = "mac.dictationLanguageMode"
    nonisolated static let translationTargetLanguage = "mac.translationTargetLanguage"
    nonisolated static let translateSelectedTextOnTranslationHotkey = "mac.translateSelectedTextOnTranslationHotkey"
    nonisolated static let globalHotkeyShortcut = "mac.globalHotkeyShortcut"
    nonisolated static let togglePanelHotkeyShortcut = "mac.togglePanelHotkeyShortcut"
    nonisolated static let translationHotkeyShortcut = "mac.translationHotkeyShortcut"
    nonisolated static let rewriteHotkeyShortcut = "mac.rewriteHotkeyShortcut"
    nonisolated static let hotkeyPreset = "mac.hotkeyPreset"
    nonisolated static let hotkeyDistinguishModifierSides = "mac.hotkeyDistinguishModifierSides"
    nonisolated static let personalDictionary = "mac.personalDictionary"
    nonisolated static let personalDictionaryEnabled = "mac.personalDictionaryEnabled"
    nonisolated static let interactionSoundsEnabled = "mac.interactionSoundsEnabled"
    nonisolated static let interactionSoundPreset = "mac.interactionSoundPreset"
    nonisolated static let launchAtLogin = "mac.launchAtLogin"
    nonisolated static let showInDock = "mac.showInDock"
    nonisolated static let hotkeyDebugLoggingEnabled = "mac.hotkeyDebugLoggingEnabled"
    nonisolated static let openAIDebugLoggingEnabled = "mac.openAIDebugLoggingEnabled"
}
