#if os(macOS)
    import AppKit
    import Foundation
    import Testing

    @testable import Stet

    @MainActor
    @Suite("Clipboard Service", .serialized)
    struct ClipboardServiceTests {
        private func makePasteboard() -> NSPasteboard {
            NSPasteboard(name: NSPasteboard.Name("StetTests.Clipboard.\(UUID().uuidString)"))
        }

        @Test func transientCopiesMarkPasteboardAsSpecial() {
            let pasteboard = makePasteboard()
            let clipboard = SystemClipboardService(pasteboard: pasteboard)

            clipboard.copy("temporary", transient: true)

            #expect(pasteboard.string(forType: .string) == "temporary")
            #expect(
                pasteboard.data(
                    forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) != nil
            )
            #expect(
                pasteboard.data(
                    forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) != nil
            )
            #expect(
                pasteboard.data(
                    forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) != nil
            )
        }

        @Test func persistentCopiesDoNotMarkPasteboardAsSpecial() {
            let pasteboard = makePasteboard()
            let clipboard = SystemClipboardService(pasteboard: pasteboard)

            clipboard.copy("persistent", transient: false)

            #expect(pasteboard.string(forType: .string) == "persistent")
            #expect(
                pasteboard.data(
                    forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) == nil
            )
            #expect(
                pasteboard.data(
                    forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) == nil
            )
            #expect(
                pasteboard.data(
                    forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) == nil
            )
        }
    }
#endif
