import Foundation

enum MacPreferences {
    nonisolated static let showPanelOnLaunch = "mac.showPanelOnLaunch"
    nonisolated static let copyToClipboardOnCapture = "mac.copyToClipboardOnCapture"
    nonisolated static let autoPasteOnCapture = "mac.autoPasteOnCapture"
    nonisolated static let revealPanelOnCapture = "mac.revealPanelOnCapture"
    nonisolated static let pauseMediaDuringDictation = "mac.pauseMediaDuringDictation"
    nonisolated static let selectedAudioInputDeviceID = "mac.selectedAudioInputDeviceID"
    nonisolated static let transcriptionProvider = "mac.transcriptionProvider"
    nonisolated static let rewriteEnabled = "mac.rewriteEnabled"
    nonisolated static let openAIBaseURL = "mac.openAIBaseURL"
    nonisolated static let translationTargetLanguage = "mac.translationTargetLanguage"
    nonisolated static let translateSelectedTextOnTranslationHotkey = "mac.translateSelectedTextOnTranslationHotkey"
    nonisolated static let openAITranslationModel = "mac.openAITranslationModel"
    nonisolated static let globalHotkeyShortcut = "mac.globalHotkeyShortcut"
    nonisolated static let togglePanelHotkeyShortcut = "mac.togglePanelHotkeyShortcut"
    nonisolated static let copyLatestCaptureHotkeyShortcut = "mac.copyLatestCaptureHotkeyShortcut"
    nonisolated static let translationHotkeyShortcut = "mac.translationHotkeyShortcut"
    nonisolated static let rewriteHotkeyShortcut = "mac.rewriteHotkeyShortcut"
    nonisolated static let hotkeyPreset = "mac.hotkeyPreset"
    nonisolated static let hotkeyDistinguishModifierSides = "mac.hotkeyDistinguishModifierSides"
    nonisolated static let personalDictionary = "mac.personalDictionary"
    nonisolated static let personalDictionaryEnabled = "mac.personalDictionaryEnabled"
    nonisolated static let interactionSoundsEnabled = "mac.interactionSoundsEnabled"
    nonisolated static let interactionSoundPreset = "mac.interactionSoundPreset"
    nonisolated static let appBranchEnabled = "mac.appBranchEnabled"
    nonisolated static let appBranchRules = "mac.appBranchRules"
    nonisolated static let historyRetentionPeriod = "mac.historyRetentionPeriod"
    nonisolated static let launchAtLogin = "mac.launchAtLogin"
    nonisolated static let showInDock = "mac.showInDock"
    nonisolated static let proxyMode = "mac.proxyMode"
    nonisolated static let customProxyScheme = "mac.customProxyScheme"
    nonisolated static let customProxyHost = "mac.customProxyHost"
    nonisolated static let customProxyPort = "mac.customProxyPort"
    nonisolated static let hotkeyDebugLoggingEnabled = "mac.hotkeyDebugLoggingEnabled"
    nonisolated static let openAIDebugLoggingEnabled = "mac.openAIDebugLoggingEnabled"
}
